FROM golang:1.23.5-alpine3.21 AS builder
WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o server .

FROM alpine:3.21
COPY --from=builder /usr/src/app/server .
CMD ["./server"]